### ISSUE TITLE
ayatana-ido doesn't agree with QMenuModel (& Gtk) on switch menu item & action

### ISSUE THREAD

**Issue by peat-psuwit** [AyatanaIndicators/qmenumodel#21]
So, in AyatanaIndicators/ayatana-ido#15, the handling of `org.ayatana.indicator.switch` menu item changed so that it now expects the corresponding action to take a parameter of type `boolean`. Then the various indicators are altered to match this (e.g. AyatanaIndicators/ayatana-indicator-bluetooth#7 and AyatanaIndicators/ayatana-indicator-display#20).

However, for QMenuModel (specifically `AyatanaMenuModel`), this breaks the functionality of the switch, since GtkMenuTrackerItem will consider the menu item "activatable" if the item has the "target", i.e. "the parameter to pass when activating the action " [1], of matching type.

https://github.com/AyatanaIndicators/qmenumodel/blob/24cc4eefb93849302985559958c5392c9ea81552/libqmenumodel/src/gtk/gtkmenutrackeritem.c#L264-L268

In the indicator PRs, the menu item doesn't get updated to has the "target" property. That means that this part of the code now consider that this menu item can't be activated, and then return.

Now, I don't feel like the "correct" way to fix this is to add the "target" property. Further down below in GtkMenuTrackerItem, you'll see why the logic that distinguish between types of item based on whether the menu item has the target and whether the action has a state. This clues us on intended use of state & action. Besides, what is the correct "action parameter" for a toggleable switch?

https://github.com/AyatanaIndicators/qmenumodel/blob/24cc4eefb93849302985559958c5392c9ea81552/libqmenumodel/src/gtk/gtkmenutrackeritem.c#L279-L289

However, changing this now would mean to revert both ayatana-ido and indicators, _and_ also any other things which now rely on the action being like it is (if there's anything as stupid as lomiri-system-settings, which I hope is minimal). So I'm not sure what should we do now. Handle this in QMenuModel instead?

The `GtkMenuTrackerItem` is actually copied from the Gtk tree. The Gtk copy has some changes, but still has the same logic [2]. So, I'm not sure if deviating from Gtk on this is a good idea. However we already has a number of commits on top of the original copy, so 🤷?

[1] https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI#Attributes
[2] https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkmenutrackeritem.c#L316

**Comment by peat-psuwit** [comment]
Hmm... I have a flash of thought on how the slider menu (e.g. the volume slider) does it, since it doesn't have an obvious "target" either.

Turns out, it uses the dummy target value of "0", and then use `g_action_group_change_action_state()` instead of action activation. Maybe we can copy this for the switch item:

- It doesn't break `ayatana-ido`, since it doesn't read the "target" value anyway.
- It unbreaks `QMenuModel`, since now it considers this action activatable.
- I still have to update Lomiri, but with `_change_action_state()` I shouldn't have to hardcode `org.ayatana.indicator.switch` in it anymore.

Will test this theory tomorrow.

EDIT: have to be aware of this logic too. Thus the dummy target value probably has to be `true`.

https://github.com/AyatanaIndicators/qmenumodel/blob/24cc4eefb93849302985559958c5392c9ea81552/libqmenumodel/src/gtk/gtkmenutrackeritem.c#L279-L283

**Comment by ghost** [comment]
I am closing this as fixed by multiple commits in multiple projects/components (see above list).
