### ISSUE TITLE
Rename Unity* symbols to Ayatana* symbols (and keep an API set of symbol aliases)

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/qmenumodel#3]
We should consider, dropping the named Unity in the qmenumodel code and switch it to something generic.

We might have to keep a set of alias symbols around for a while (until Unity8 has fully shifted over to Lomiri). Ideally with deprecation warnings.

**Comment by peat-psuwit** [comment]
I wonder if there exists _any_ user of non-Unity QDBusMenuModel at all?

https://github.com/AyatanaIndicators/qmenumodel/commit/4fc790c377f4ca154ea5fc8beca6fd9078edf2ee#diff-5f01046160c43e67533a3dbdc2881e4cffaa34f157c1b6659e49cc25f0bd3f6f

> UnityMenuModel serves the same purpose as QMenuModel, but it is based on
GtkMenuTracker and has a different API.
